### ISSUE TITLE
Crew member and pet disappearance during travel

### ISSUE THREAD

**Issue by zenith408** [SmashPhil/Boats#7]
During caravell's travel on global map (after several in-game time, about one day), a one of crew members suddenly became the naked prisoner (and also a prison camp with him has appeared on a map), and pets onboard just disappeared without any signs.

**Comment by SmashPhil** [comment]
Any error log? What do you mean naked prisoner? That one of the naked prisoners moved to a crew member spot? I fixed a bug where non colonists would try to reseat into crew member spots. It will be released in the next update, which will be soon (like next week soon).  For now I would just be careful about bringing a caravel with empty crew slots like cannons while also having pets or prisoners.

**Comment by zenith408** [comment]
There was no errors (no auto-opened log). A mentioned prisoner initially was a colonist and a crew member. During travel ship had several colonists and pets onboard, but no prisoners on anything else. While ship was travelling on planet map, i got a message about prisoner (typical rimworld event). I looked at this message, and found that this prisoner was exactly the man from crew. Then i checked the caravan, and saw that this crew member is still onboard, but now counts as a prisoner and lost every item but his rifle. 
Speaking simplier, it was something like this:
1) Make caravan with ship, pets and crew; send it somewhere;
2) See a message about prisoner asking for help;
3) Check the caravan, find that pets are gone, and one of the crew members became the prisoner.

**Comment by SmashPhil** [comment]
okay I'm sorry but that's hilarious lol this is definitely fixed in the next update though. I can give you an explanation to what happened. So the game stores world pawns under certain categories right? None, Free, Dead, FactionLeader, Kidnapped, CaravanMember, InTravelingTransportPod, and ForSaleBySettlement. That's how it keeps track of pawns that were despawned but should still be saved within the game. Well.. since boats aren't technically speaking... well... anything related to normal world pawn mechanics, it automatically stored them as Free world pawns. Meaning the game can pull from those world pawns for stuff like your Prisoner event.  They are stored as CaravanMembers now though (next update) so this won't happen anymore. 

Update will be released in a few days. I'm adding a few more things on top of this fix.  Tbh though, you got really unlucky. Not only did you get the perfect event to pull from free pawns, it pulled YOUR free pawn.  Sorry mate

**Comment by SmashPhil** [comment]
New update is pushed :)

**Comment by zenith408** [comment]
It seems that this bug strikes back. (translating the text on a screenshot - there is a caravan with pawn named Rodat and a message about the prisoner - which is Rodat)
By the way, i forgot to mention another strange feature of this bug - a message about prisoner contains no name of pawn's backstory. (where is a sign "Rodat -- .", there is should be something like "Rodat is a {Adult_Backstory_name}")
![изображение](https://user-images.githubusercontent.com/58828364/71421943-3df70880-268f-11ea-9751-4e439ed8fb2c.png)
